version: '3'

volumes:
  pg:
  static:
  media:


services:
  db:
    image: postgres:13
    restart: always
    env_file: ../.env
    volumes:
      - pg:/var/lib/postgresql/data
  backend:
    image: andreiklevtsov/foodgram_backend
    restart: always
    env_file: ../.env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: andreiklevtsov/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - ./frontend/:/app/result_build/
  gateway:
    image: nginx:1.19.3
    depends_on:
      - backend
    env_file: ../.env
    restart: always
    ports:
      - "8080:80"
    volumes:
      - static:/static/
      - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/